---
abstract: 'The great new RT::Extension::SetOwnerRequestorToCurrentUserForTicketCreate!'
author:
  - 'Matt Zagrabelny, C<< <mzagrabe at d.umn.edu> >>'
  - 'Matt Zagrabelny <mzagrabe@d.umn.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-SetOwnerRequestorToCurrentUserForTicketCreate
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=RT-Extension-SetOwnerRequestorToCurrentUserForTicketCreate
  license: http://www.gnu.org/licenses/gpl-2.0.html
version: '0.01'
